export const subregions = [
  'No subregion',
  'Australia and New Zealand',
  'Caribbean',
  'Central Africa',
  'Central America',
  'Central Asia',
  'Eastern Africa',
  'Eastern Asia',
  'Eastern Europe',
  'Melanesia',
  'Micronesia',
  'Middle Africa',
  'Northern Africa',
  'Northern Europe',
  'Polynesia',
  'South America',
  'South-Eastern Asia',
  'Southern Africa',
  'Southern Asia',
  'Southern Europe',
  'Southeast Europe',
  'Western Africa',
  'Western Asia',
  'Western Europe'
] as const
